name: "GitHub CI *Bsd merge checks"

on:
  push:
    branches: [ "auto", "github-actions-merge-tests" ]

env:
  PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
  CHECKOUT_FETCH_DEPTH: 1001

jobs:
  freebsd:
    runs-on: ubuntu-latest
    if: false # issues with linking

    steps:
      - name: Checkout Sources
        uses: actions/checkout@v4
        with:
          fetch-depth: ${{ env.CHECKOUT_FETCH_DEPTH }}

      - name: Test in FreeBSD
        id: test-freebsd
        uses: vmactions/freebsd-vm@v1
        with:
          usesh: true
          sync: sshfs
          # release: "14.1" # supported: 12.4, 13.2, 13.3, 14.1
          prepare: |
            pkg install -y \
              autoconf \
              autoconf-archive \
              automake \
              bash \
              cppunit \
              gmake \
              libltdl \
              libtool \
              libxml2 \
              m4 \
              nettle &&
            df .

          run: |
            export MAKE=gmake
            export CFLAGS='-Wno-compound-token-split-by-macro'
            export CC=clang
            export CXX=clang++
            ./test-builds.sh --verbose

      - name: Publish build logs
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          path: btlayer-*.log

  openbsd:
    runs-on: ubuntu-latest
    if: false # currently failing with permission problems in ltdl

    steps:
      - name: Checkout Squid sources
        uses: actions/checkout@v4
        with:
          fetch-depth: ${{ env.CHECKOUT_FETCH_DEPTH }}

      - name: Test
        id: test
        uses: vmactions/openbsd-vm@v1
        with:
          usesh: true
          sync: sshfs
          prepare: |
            pkg_add \
              autoconf-2.72p0 \
              automake-1.16.5 \
              bash \
              coreutils \
              cppunit \
              git \
              ggrep \
              gmake \
              libxml \
              libtool \
              m4 \
              metaauto
            mkdir $HOME/bin
            ln -s /usr/local/bin/ggrep $HOME/bin/grep
            ls -ld /usr/local/share/aclocal*
            ls -l /usr/local/bin/auto*

          run: |
            export MAKE=gmake
            export pjobs="-j`gnproc`"
            export AUTOMAKE_VERSION=1.16
            export amver=${AUTOMAKE_VERSION}
            export ACLOCAL_AUTOMAKE_DIR="/usr/local/share/aclocal-${AUTOMAKE_VERSION}"
            export ACLOCAL_PATH="/usr/local/share/aclocal:/usr/local/share/aclocal-${AUTOMAKE_VERSION}"
            export AUTOCONF_VERSION=2.72
            export acver=${AUTOCONF_VERSION}
            export ltver=2.4.2
            export CFLAGS='-Wno-compound-token-split-by-macro'
            export LDFLAGS="-L/usr/local/lib"
            export PATH="$HOME/bin:$PATH"
            ./test-builds.sh --verbose

      - name: Publish build logs
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          path: btlayer-*.log
